name: memegenerator
description: 'Create your own meme'
publish_to: 'none'
version: 1.0.2+4
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  in_app_update: ^4.2.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  rxdart: ^0.27.7
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.10
  carapacik_lints: ^1.8.1
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

flutter_launcher_icons:
  image_path: "assets/app/ic_logo.png"
  android: true
  adaptive_icon_background: "assets/app/ic_background.png"
  adaptive_icon_foreground: "assets/app/ic_foreground.png"
  min_sdk_android: 24
  ios: true

flutter_native_splash:
  color: "#FFE600"
  image: "assets/app/splash.png"
  android: true
  ios: true
