name: memogenerator
description: Generate meme

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+4
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.11
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  lint: ^1.8.1

flutter:
  uses-material-design: true