name: memogenerator
description: Generate meme

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  provider: ^6.0.1
  rxdart: ^0.27.2
  uuid: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true