name: memegenerator
description: Create your own meme
publish_to: 'none'
version: 1.0.1+3
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  google_fonts: ^2.3.2
  image_picker: ^0.8.5+3
  in_app_update: ^3.0.0
  json_annotation: ^4.5.0
  path_provider: ^2.0.10
  provider: ^6.0.2
  rxdart: ^0.27.3
  screenshot: ^1.2.3
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  carapacik_lints:
    git:
      url: https://github.com/Carapacik/carapacik_lints.git
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  icons_launcher: ^1.1.7
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

flutter_icons:
  image_path: 'assets/ic_logo.png'
  adaptive_icon_background: 'assets/ic_background.png'
  adaptive_icon_foreground: 'assets/ic_foreground.png'
  remove_alpha_ios: false
  android: true
  ios: true

flutter_native_splash:
  color: '#FFE600'
  image: 'assets/splash.png'
  android: true
  ios: true
  fullscreen: true
