name: memogenerator
description: Generate your meme
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  image_picker: ^0.8.4+11
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  rxdart: ^0.27.3
  screenshot: ^1.2.3
  share_plus: ^3.1.0
  shared_preferences: ^2.0.13
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  lint: ^1.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/